### ISSUE TITLE
Setting conf attributes via command line without existing DB on disk does not write full DB to disk

### ISSUE THREAD

**Issue by jkdelauney** [c-hudson/teenymush#7]
If the `-D<conf attribute>` command-line argument is used to set options when a DB has not yet been written to disk only a change log without a filename is written to disk instead of a full DB.

This seems to be a result of the first full DB write happening when `spin()` is called and that function never gets called when a command-line argument is parsed.

**Comment by c-hudson** [comment]
Fixed. A full dump is now performed if the db has never been written when setting -Dconf attributes from the command line instead of an incremental dump.
